### ISSUE TITLE
Download Button doesn't work

### ISSUE THREAD

**Issue by atmickle** [frictionlessdata/datapackage-ui#259] opened 2018-09-12 14:56 UTC
I have two resources loaded into my package, but the Download button doesn't do anything. I'm not seeing any errors or messages.

**Comment by roll** [comment] 2020-04-02 11:48
Sorry for the inconvenience!

I have to close this issue now because the button works fine at the moment on all the data packages I have tested.

If it's still actual, please re-open with details of reproducing the problem.

**Closed by roll** 2020-04-02 11:48 UTC
Labels: bug
